# Generated by Django 4.1.5 on 2023-02-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='age',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='role',
            field=models.CharField(blank=True, default='Soft User', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='year_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
